include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/injection/injection.config.dart
linter:
  rules:
    public_member_api_docs: false
