name: puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  build_runner: ^2.1.7
  cloud_firestore: ^3.1.7
  cool_alert: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  get_storage: ^2.0.3
  image: ^3.1.1
  injectable: ^1.5.3
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  speech_to_text: ^5.4.2

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
dependency_overrides:
  analyzer: ^3.2.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/puzzles/
